development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: goalpact_development
  pool:     5
  username: goalpact

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: goalpact_test
  pool:     5
  username: goalpact

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: goalpact_production
  pool:     5
  username: goalpact